# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e0b55d7b0f55acf6efad3dfb484ec9c9"
name = "first-task"
handle = "first-task-1"
application_url = "https://nut-married-contains-individually.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "complexdiscount.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://nut-married-contains-individually.trycloudflare.com/auth/callback",
  "https://nut-married-contains-individually.trycloudflare.com/auth/shopify/callback",
  "https://nut-married-contains-individually.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
